### PR TITLE
Add `prettier` and `lint-staged` deps to keep files inline with `.editorconfig`

### PR DESCRIPTION
**Pull request by kelfish**
*Changes*
- Add `prettier` as a dependency and config files
- Add `lint-staged` and `husky` to run `prettier` and `eslint` on `pre-commit`
- Bring all existing inline with `.editorconfig` and `.prettierrc` to ensure tabbing and layout is standard

_NOTE: Some files were `2` spaces for indents, some where `4`, but I stuck with the `.editorconfig` setup of `2`. Also some discrepancies between `'` and `"`_

### CODE REVIEW

**Comment by de-luca** [comment]
Thank you for the PR.
However, for personal reasons, I wont take in husky.

**Comment by kelfish** [comment]
I've replaced `husky` with `simple-git-hooks`. Does this work?

ref: https://github.com/toplenboren/simple-git-hooks

**Comment by de-luca** [comment]
I'm sorry, what I meant is that I'm against these tools that hijack workflows.
I prefer this to be either up to the devs and/or the CI

**Comment by kelfish** [comment]
Understood, I flip flop between the two approaches, so I get it. Will remove the `pre-commit` automation...

**Comment by kelfish** [comment]
I've removed the `pre-commit` git hook approach and added extra `eslint` rules so CI can flag anything that conflicts with `editorconfig` and `prettier`

**Comment by de-luca** [comment]
Thank you a lot!

**Pull request merged**
